import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { AlertProvider } from '@/context/alert'
import { AuthProvider } from '@/context/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AlertProvider>
            {' '}
            {/* ModalProvider로 children을 감쌉니다. */}
            <Navbar />
            <main>{children}</main>
            <footer className="bg-gray-800 p-4 text-white text-center">Global Footer</footer>
          </AlertProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
